### PR TITLE
Retrofit extensions

### PR DESCRIPTION
**Pull request by lucassales2**

### CODE REVIEW

**Comment by vladostaci** [comment]
I suggest to rename the extension files like this: ClassNameEx
Ex: TextViewEx, RetrofitEx.
We're already using this style in multiple projects.
Also all the extension files should be placed in *extensions* directory.

**Comment by lucassales2** [comment]
Thanks @vladostaci, I'll move them to a different directory, on PR #36 I changed the name of the files too

**Comment by vladostaci** [comment]
> Thanks @vladostaci, I'll move them to a different directory, on PR #36 I changed the name of the files too

Great job Lucas 👍

**Comment by lucassales2** [comment]
Will be added on #34 Branch

**Pull request closed without merging**
